import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true
window.opacity = 1.0

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.dimensions]
columns = 200
lines = 50
